-- Rename the visibility mode `private` → `internal` (architecture §4.2).
--
-- The old name overpromised. The whole check in the edge gate was "is there a
-- session at all" (`visibilityAllows`, apps/edge/src/auth/validate.ts) — it never
-- looked at *which* principal signed in, so the mode has always meant "any
-- authenticated directory user", i.e. internal. This is a pure rename: every app
-- keeps exactly the gate it had, and `internal` becomes the default for new apps.
--
-- The name `private` is being freed for a real owner-plus-platform-admins mode
-- later. That needs a principal identifier the data and control planes do not yet
-- share (the edge session's `oid` is the edge OIDC client's `sub`; `App.ownerId`
-- is the portal actor's — different spaces under Entra's pairwise `sub`), so the
-- label is left out of the enum entirely rather than reserved: a mode no plane can
-- evaluate would fall through the gate and deny everyone, owner included.
--
-- RENAME VALUE rather than ADD + UPDATE + DROP. It relabels the type and every
-- existing row atomically, so there is no backfill and no window where rows carry
-- a label the enum no longer has. Safe here because the label is referenced only
-- by the CREATE TYPE in 20260611235025_init — no view, function, check constraint,
-- or column default mentions it. (Note the ADD VALUE path could not have done the
-- UPDATE in this same migration anyway: Postgres forbids using a new enum label in
-- the transaction that added it.)
--
-- Deploy ordering, accepted deliberately: this is not expand/contract, so during a
-- rolling release a replica still on the previous image reads `internal`, does not
-- recognise it, and its gate falls through to deny. That is fail-closed (never
-- fail-open) and self-heals as replicas cycle onto the new image — so run this
-- migration job as part of the same release as the images, not ahead of it.
--
-- Raw migration: Prisma emits a destructive drop/recreate for an enum member
-- change. Same hand-written precedent as 20260730001500_app_secrets_admin_scope_unique.
ALTER TYPE "VisibilityMode" RENAME VALUE 'private' TO 'internal';
